### ISSUE TITLE
Remove hardcoded trustee images tags/digests

### ISSUE THREAD

**Issue by lmilleri** [confidential-containers/trustee-operator#48]
Currently the trustee images to be deployed by the operator are hardcoded [here](https://github.com/confidential-containers/trustee-operator/blob/9e4b0d15cfc53ad68248535d11d134a5c7ade5d9/config/manager/manager.yaml#L85C1-L93C75) .

A more flexible mechanism will be beneficial to the deployment and test automation.

Suggested solution: [Define container environment variables using ConfigMap data](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)

**Comment by lmilleri** [comment]
It looks like the suggested approach will complicate things downstream when defining the images to be used (new config map with tags/digests to be created by the user). @bpradipt is suggesting to check for the "kustomize patch" approach.

**Comment by lmilleri** [comment]
Something like this does the trick:

```
kustomize edit add patch --patch '- op: replace
  path: "/spec/template/spec/containers/0/env/1"
  value:
    name: KBS_IMAGE_NAME
    value: quay.io/confidential-containers/trustee:290fd0eb64ab20f50efbd27cf80542851c0ee17f' --kind Deployment --name controller-manager

```
